version: '2.1'

services:
  bluetick:
    image: bluetick
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    links:
      - bluetick-db
    depends_on:
      - bluetick-db
  bluetick-db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"